# Generated by Django 6.0 on 2025-12-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpeedTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "download_speed_mbps",
                    models.FloatField(
                        help_text="Download speed in Megabits per second (Mbps)"
                    ),
                ),
                (
                    "upload_speed_mbps",
                    models.FloatField(
                        help_text="Upload speed in Megabits per second (Mbps)"
                    ),
                ),
                (
                    "latency_ms",
                    models.FloatField(
                        help_text="Round-trip time (ping) in milliseconds"
                    ),
                ),
                (
                    "jitter_ms",
                    models.FloatField(help_text="Variance in latency in milliseconds"),
                ),
                (
                    "isp_name",
                    models.CharField(
                        help_text="Detected Internet Service Provider", max_length=255
                    ),
                ),
                (
                    "is_starlink",
                    models.BooleanField(
                        default=False,
                        help_text="True if the ISP is identified as Starlink",
                    ),
                ),
                (
                    "client_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Public IP address of the client",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
